name: Python package
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  call_python_package_build:
    name: Build and test Python package
    uses: szikszail/workflows/.github/workflows/python-package-build.yml@main
    with:
      coverage_path: coverage.lcov
      coverage_format: clover